### ISSUE TITLE
checklist items for lecture 3

### ISSUE THREAD

**Issue by tuvelofstrom** [Civil-Data/Bomb-IT#52]
## Lecture 3 --- Using version control software (Git)

Carry on with the project implementation.
Create a revert commit to revert a change.
Create a branch to implement a small feature then merge it.

Checklist:

* [x] Add a `.gitignore` file to your project
* [x] Has a revert commit (don't edit history: create a new revert commit!).
* [x] Has a branch implementing a small feature.
* [x] Has a merge commit (of the branch)
* [x] Has a branch in conflict with main/master 
* [x] Try to merge and resolve the merge conflict
* [x] Has working compilation and running instructions in the README.
* [x] Has issues associated with each of your changes.

**Comment by tuvelofstrom** [comment]
Well done!
